float:
  euclidean:
  - base_args: ['@metric']
    constructor: ParlayANN
    disabled: false
    docker_tag: ann-benchmarks-parlayann
    module: ann_benchmarks.algorithms.parlayann
    name: parlayann
    run_groups:
      parlay_64:
        args: [{alpha: 1.15, R: 64, L: 128, two_pass: True}]
        query_args: [[{limit: 10}, {limit: 11}, {limit: 12}, {limit: 13}, {limit: 14}, {limit: 15},
                      {Q: 10}, {Q: 11}, {Q: 12}, {Q: 13}, {Q: 14}, {Q: 15}, {Q: 16}, {Q: 17}, {Q: 18}, {Q: 19}, {Q: 20}, {Q: 21}, {Q: 22}, {Q: 23}, {Q: 25}, {Q: 30}, {Q: 40}, {Q: 50}, {Q: 60}, {Q: 80}, {Q: 100}, {Q: 200}, {Q: 500}, {Q: 750}]]
      parlay_40:
        args: [{alpha: 1.15, R: 40, L: 80, two_pass: True}]
        query_args: [[{limit: 10}, {limit: 11}, {limit: 12}, {limit: 13}, {limit: 14}, {limit: 15},
                      {Q: 10}, {Q: 11}, {Q: 12}, {Q: 13}, {Q: 14}, {Q: 15}, {Q: 16}, {Q: 17}, {Q: 18}]]


